//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipMoveType
    {
        public int Id { get; set; }
        public int ShipId { get; set; }
        public Nullable<bool> WhitPacking { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<int> PickupStories { get; set; }
        public Nullable<bool> ElevatorPickup { get; set; }
        public Nullable<int> DeliveryStories { get; set; }
        public Nullable<bool> ElevatorDelivery { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
